# .github/workflows/docker-build.yml

name: Build and Push Docker Images

on:
  push:
    branches:
      - main      # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main      # Trigger on pull requests targeting the main branch

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Find Dockerfiles and prepare the matrix
      - name: Find Dockerfiles and Set Matrix
        id: set-matrix
        run: |
          echo "Finding all Dockerfiles..."
          # Find all Dockerfiles recursively
          dockerfiles=$(find . -type f -name 'Dockerfile')

          if [ -z "$dockerfiles" ]; then
            echo "No Dockerfiles found."
            echo "matrix={}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Initialize JSON for matrix
          json="{\"dockerfiles\": ["
          first=true

          for df in $dockerfiles; do
            dir=$(dirname "$df")
            # Extract the folder name to use as the image name
            image_name=$(basename "$dir")
            # Replace any spaces or special characters with hyphens
            image_name=$(echo "$image_name" | tr ' ' '-')

            if [ "$first" = true ]; then
              first=false
            else
              json+=", "
            fi

            # Add each Dockerfile details to the matrix
            json+="{\"path\": \"$df\", \"context\": \"$dir\", \"image_name\": \"$image_name\"}"
          done

          json+="]}"
          echo "Matrix JSON: $json"
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build-and-push:
    needs: set-matrix
    runs-on: ubuntu-latest
    if: ${{ needs.set-matrix.outputs.matrix != '{}' }}
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.path }}
          push: true
          tags: |
          lazarevcloud/${{ matrix.image_name }}:latest
          lazarevcloud/${{ matrix.image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64  # Adjust based on your needs
