name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Dockerfiles and Set Matrix
        id: set-matrix
        run: |
          echo "Finding Dockerfiles..."
          json="{\"dockerfiles\":["
          first=true
          
          while IFS= read -r -d '' df; do
            dir=$(dirname "$df")
            # Sanitize image name more strictly
            image_name=$(basename "$dir" | sed 's/[^a-zA-Z0-9.-]/-/g' | tr '[:upper:]' '[:lower:]')
            # Ensure valid start character
            if [[ ! $image_name =~ ^[a-z0-9] ]]; then
              image_name="app-${image_name}"
            fi
            # Remove any invalid patterns
            image_name=$(echo "$image_name" | sed 's/-\+/-/g' | sed 's/^\.|\.$//')
            
            if [ "$first" = true ]; then
              first=false
            else
              json+=","
            fi
            
            json+="{\"path\":\"$df\",\"context\":\"$dir\",\"image_name\":\"$image_name\"}"
          done < <(find . -type f -name 'Dockerfile' -print0)
          
          json+="]}"
          echo "matrix=$json" >> $GITHUB_OUTPUT
          echo "Matrix JSON: $json"

  build-and-push:
    needs: set-matrix
    runs-on: ubuntu-latest
    if: ${{ needs.set-matrix.outputs.matrix != '{"dockerfiles":[]}' }}
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.path }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            lazarevcloud/${{ matrix.image_name }}:latest
            lazarevcloud/${{ matrix.image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          provenance: false